import Head from 'next/head'
import styles from '../styles/home.module.scss'
import Image from 'next/image'
import { Swiper, SwiperSlide} from 'swiper/react';
import { Autoplay } from 'swiper';
import 'swiper/css';
import { Josefin_Sans } from 'next/font/google';
import Layout from '../components/layout/layout'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFilter,faCommentDots,faGreaterThanEqual,faMagnifyingGlass,faChevronDown } from '@fortawesome/free-solid-svg-icons'
import PageDown from '@/components/pageDownButton/pageDownButton';
import VersusPage from '@/components/versusPage/versusPage';

const josefinSans = Josefin_Sans({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>BeerLocator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Layout>
      <main className={josefinSans.className}>
				<div className={styles.container}>
					<div className={styles.introContainer}>
						<div className={styles.introImage}>
						<Swiper
						  loop={true}
							modules={[Autoplay]}
							autoplay={{delay:1000}}
							spaceBetween={50}
							slidesPerView={1}
							onSlideChange={() => console.log('slide change')}
							onSwiper={(swiper) => console.log(swiper)}
    				>
      <SwiperSlide><Image src="/corona.png" alt="corona" width={300} height={150}/></SwiperSlide>
      <SwiperSlide><Image src="/budweiser.png" alt="budweiser"  width={300} height={150}/></SwiperSlide>
      <SwiperSlide><Image src="/heineken.png" alt="heineken"  width={300} height={150}/></SwiperSlide>
      <SwiperSlide><Image src="/hoegaarden.png" alt="hoegaarden"  width={300} height={150}/></SwiperSlide>
    				</Swiper>
							<Image src="/emojiThinking.png" alt="emojiThinking" width={300} height={300}/>
						</div>
						<div className={styles.introDescription}>
							<h2>Let's find your dream beer</h2>
							<div className={styles.description}>
								<span><p className={styles.descriptionText}>Tired of the usual beer? So let us help you find the beer of your dreams.</p></span>
							<div className={styles.workDescription}>
								<h2>That's how we can help</h2>

								<div className={styles.workExamples}>
									<div>
									<div className={styles.icon}>
									<FontAwesomeIcon icon={faFilter} />
									</div>
									<span>filter a beer you like</span>
									</div>

									<div>
									<div className={styles.icon}>
										<FontAwesomeIcon icon={faGreaterThanEqual} />
									</div>
									<span>Compare your favorite drinks</span>
									</div>

									<div>
									<div className={styles.icon}>
									<FontAwesomeIcon icon={faMagnifyingGlass} />
									</div>
									<span>Expand your taste preferences</span>
									</div>

									<div>
									<div className={styles.icon}>
									<FontAwesomeIcon icon={faCommentDots} />
									</div>
									<span>Leave and read reviews on the beer </span>
									</div>

								</div>
							</div>
							</div>
	
						</div>
					</div>

<PageDown/>


				</div>
				<VersusPage/>
      </main>
			</Layout>
    </>
  )
}
